version: "3"

services:
  app:
    container_name: voicecollector
    restart: always
    build: .
    env_file:
      - docker.env
    ports:
      - "127.0.0.1:47001:5000"
    links:
      - mongo-audioRecords

  mongo-bookme:
    container_name: mongo-audioRecords
    image: mongo
    volumes:
      - mongodb://localhost:27017/audioRecords